# test-repository-1/.github/workflows/call-reusable-create-file.yml
name: Trigger â€” create file, PR, and merge

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "File to create"
        required: true
        default: "dummy.txt"
      file_content:
        description: "Content of the file"
        required: true
        default: "This file was created by org-level-automation-app."
      base_branch:
        description: "Target base branch"
        required: false
        default: "main"

jobs:
  call-reusable:
    uses: engineering-organization/gha-actions/.github/workflows/create-file-pr-merge.yml@main
    with:
      filename: ${{ inputs.filename }}
      file_content: ${{ inputs.file_content }}
      base_branch: ${{ inputs.base_branch }}
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
